#!/bin/sh

# alias
git config --global alias.last 'log -1 HEAD'
git config --global alias.oneline "log --graph --pretty=format:'%Cred%h%Creset -%C(bold yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
git config --global alias.co checkout
git config --global alias.br branch
git config --global alias.ci commit
git config --global alias.st status
git config --global alias.sts 'status -s'
git config --global alias.unstage 'reset HEAD --'
git config --global alias.discard 'checkout --'


# rerere
git config --global rerere.enabled true
